// import { Pay } from '@cashier_alipay/cashiersdk'

// export interface RequestPaymentOptions {
// 	orderInfo : string
// }

// export function requestPayment(options : RequestPaymentOptions) {
// 	return new Pay().pay(options.orderInfo, true)
// }

import { MqttAsync } from '@ohos/mqtt'
import { type MqttClientOptions } from '@ohos/mqtt/src/main/cpp/types/libmqttasync'

export function mqttUtil(options: MqttClientOptions) {
	return MqttAsync.createMqtt(options)
}
