/*
 * interface.uts
 * TibetanTranslator
 * Created by: Administrator
 * Copyright (c) 2024. 武汉帧迹科技有限公司
 * 武汉帧迹科技有限公司 版权所有，不得私自使用，拷贝，修改，删除，否则视为侵权。
 * Copyright belongs to MVTrail Tech CO.,LTD.  All rights reserved.
 * Email: support@mvtrail.com
 */

/**
 * interface.uts
 * uts插件接口定义文件，按规范定义接口文件可以在HBuilderX中更好的做到语法提示
 */

/**
 * myApi 异步函数的参数，在type里定义函数需要的参数以及api成功、失败的相关回调函数。
 */

export interface Uni {
	readFileAsDataURL(filePath:string): Promise<string>,
}