/*
 * index.uts
 * TibetanTranslator
 * Created by: Administrator
 * Copyright (c) 2024. 武汉帧迹科技有限公司
 * 武汉帧迹科技有限公司 版权所有，不得私自使用，拷贝，修改，删除，否则视为侵权。
 * Copyright belongs to MVTrail Tech CO.,LTD.  All rights reserved.
 * Email: support@mvtrail.com
 */

export function readFileAsDataURL(filePath:string):Promise<string> {
    return new Promise((resolve, reject)=>{
        console.warn("unsupport in web",filePath)
        resolve("")
    })
}