<template>
	<view>
		<button @click="click">click</button>
	</view>
</template>


<script>
	export default {
		data() {
			return {
				ls: []
			}
		},
		methods: {
			click() {
				// 192.168.31.148
				// const ls = []
				const data = [{
					"biz": "",
					"bizBz": "",
					"bzqSl": null,
					"bzqSlLx": "",
					"bzqYjts": null,
					"canZnydh": "",
					"cbjQjfs": "",
					"cc": "",
					"ccMc": "",
					"ccStr": [],
					"cgsl": "",
					"cgzje": null,
					"chjjfs": "",
					"ckId": "",
					"ckMc": "",
					"ckjMrfs": "",
					"ckmrj": 81,
					"cksl": null,
					"cktrdjBz": "",
					"ckxxList": [],
					"clientPlatform": "",
					"copyTag": "",
					"count": null,
					"createBy": null,
					"createDate": "2024-08-01 15:05:56",
					"createId": "",
					"crkjgBz": "",
					"currUserId": "",
					"cwHjh": "",
					"dbName": "",
					"dcksl": 33,
					"ddwFlag": "1",
					"ddwStr": "[{\"jycbj\":\"\",\"fzjlNum\":\"0\",\"dw\":\"8487582d4f0f44af98629b56d7d875f0\",\"dwMc\":\"件\",\"fzjl\":\"\",\"jycgj\":45.16,\"jylsj\":\"110.0\",\"jbdw\":\"1\",\"fzjlMc\":\"\",\"mrdw\":\"1\",\"jyxsj\":\"81\"},{\"jycbj\":\"\",\"fzjlNum\":\"0\",\"dw\":\"59d83f6c9f8149ffa530fad2617b7af0\",\"dwMc\":\"箱\",\"fzjl\":\"\",\"jycgj\":\"436.38\",\"jylsj\":\"660.00\",\"fdwNum\":\"6\",\"fzjlMc\":\"\",\"mrdw\":\"0\",\"jyxsj\":\"486.00\"}]",
					"delFlag": "0",
					"dgBz": "1",
					"djrq": "",
					"dlsId": "",
					"dlsMc": "",
					"dpjgBz": "",
					"drksl": 18,
					"dsBz": "1",
					"dw": "8487582d4f0f44af98629b56d7d875f0",
					"dwMc": "件",
					"dwYxxsBz": "0",
					"dwcb": null,
					"enableFlag": "1",
					"ext1": "",
					"ext10": "",
					"ext2": "",
					"ext3": "",
					"ext4": "",
					"ext5": "",
					"ext6": "",
					"ext7": "",
					"ext8": "",
					"ext9": "",
					"extId": "",
					"fcHjhBz": "",
					"fcxx": "",
					"fcyj": "",
					"fdwNum": 1,
					"fflbId": "",
					"fjBz": "0",
					"fjSpId": "",
					"flbId": "0",
					"fullOrgCodes": "",
					"fullOrgMcs": "",
					"fullSplbMc": "",
					"ggList": [],
					"ggsx1Id": "",
					"ggsx2Id": "",
					"ggsx3Id": "",
					"ggxh": "",
					"gldlkcBz": "",
					"gxGs": null,
					"gxSxfy": null,
					"gysId": "",
					"gysMc": "",
					"hasKc": "",
					"hasTxm": "",
					"hdLsj": null,
					"hyFlag": "",
					"hyStr": "[{\"djId\":\"a94ab268f8d94677b13b537f0b5ec83f\",\"djMc\":\"注册会员\",\"hyzk\":\"\",\"hypfj\":\"\",\"hyxsj\":\"\"},{\"djId\":\"843b7ef6ba7b4b08887a5cfd8b424eb8\",\"djMc\":\"铜牌会员\",\"hyzk\":\"\",\"hypfj\":\"\",\"hyxsj\":\"\"},{\"djId\":\"56273ccd43bb403399da2e719ca2601f\",\"djMc\":\"银牌会员\",\"hyzk\":\"\",\"hypfj\":\"\",\"hyxsj\":\"\"},{\"djId\":\"1b2973ec47ce425cb6665e795251316f\",\"djMc\":\"金牌会员\",\"hyzk\":\"\",\"hypfj\":\"\",\"hyxsj\":\"\"},{\"djId\":\"bbf1cc5b135d440db15691a414e8e4dd\",\"djMc\":\"钻石会员\",\"hyzk\":\"\",\"hypfj\":\"\",\"hyxsj\":\"\"}]",
					"id": null,
					"idList": [],
					"insertSpxxList": [],
					"isFooter": false,
					"isNewRecord": false,
					"isUpdate": false,
					"jhSl": 10,
					"jycbj": null,
					"jycgj": 45.16,
					"jylsj": 110,
					"jyxsj": 81,
					"kcId": "",
					"kcList": [],
					"kccb": "",
					"kcmxList": [],
					"kcsl": 3,
					"kcyjglBz": "",
					"kcyjsx": null,
					"kcyjsxJbdw": null,
					"kcyjxx": null,
					"kcyjxxJbdw": null,
					"khId": "049b88263ef9474a8e30265a500b1532",
					"kjckfw": "",
					"kqSpysBz": "",
					"kqpchBz": "0",
					"kqxlhBz": "0",
					"kqysBz": "0",
					"kqyxqBz": "0",
					"kykcsl": -30,
					"limit": null,
					"lstcfs": "0",
					"lstcsz": 0,
					"mdJylsj": null,
					"mode": "",
					"mrDcksl": "33件",
					"mrDrksl": "18件",
					"mrJycbj": null,
					"mrJycgj": 45.16,
					"mrJylsj": 110,
					"mrJyxsj": 81,
					"mrKcsl": "3件",
					"mrKykcsl": "-30件",
					"mrdw": "8487582d4f0f44af98629b56d7d875f0",
					"mrdwMc": "件",
					"mrdwYxxsBz": "0",
					"mxext1": "",
					"mxext10": "",
					"mxext2": "",
					"mxext3": "",
					"mxext4": "",
					"mxext5": "",
					"mxext6": "",
					"mxext7": "",
					"mxext8": "",
					"mxext9": "",
					"oldSpBh": "SP0001",
					"openId": "",
					"order": "",
					"orgCode": "",
					"orgId": "",
					"orgMc": "",
					"page": 1,
					"parentSplbId": "",
					"pch": "",
					"pkDj": null,
					"prefix": "",
					"px": 100,
					"pxfs": "",
					"pxgz": "",
					"pyDj": null,
					"qcjbdwsl": "",
					"qcsl": "",
					"qczj": null,
					"qczt": "",
					"qyId": "",
					"qyVersion": "",
					"qydm": "",
					"qydz": "",
					"qymc": "",
					"qyzt": "1",
					"remarks": "",
					"rkjMrfs": "",
					"rkmrj": 45.16,
					"rksl": null,
					"rows": 10,
					"sccgj": null,
					"scene": "",
					"scrwBz": "1",
					"scrwcbjMrfs": "",
					"scxsj": null,
					"shortId": "",
					"showLsj": "",
					"showShopInfo": "",
					"showXsj": "",
					"sl": 1,
					"slXsw": 3,
					"sortName": "",
					"spBh": "SP0001",
					"spId": "583655b081334f6cb4bbe8b701a3c0f7",
					"spIdList": [],
					"spLb": "f35c79ffb7904cf98cae6fc8cf601055",
					"spMc": "示例商品",
					"spZt": "",
					"spcxMc": "",
					"splbId": "",
					"splbMc": "成品",
					"splbMcs": "",
					"sppp": "",
					"spppId": "",
					"spsl": "",
					"sptpdz": "http://img.loafish.com/107112/SPXX/83f4c0b4edbbd3bb013112458f739f6c.png?imageView2/0/format/jpg ",
					"sptxUrl": "http://img.loafish.com/107112/SPXX/83f4c0b4edbbd3bb013112458f739f6c.png?imageView2/0/format/jpg ",
					"sptxm": "698798712",
					"sptxmdz": "",
					"spxc": "",
					"spxcDataList": [],
					"spxcs": [],
					"spxgbz": "",
					"spxxList": [],
					"spxzs": "",
					"spysList": [],
					"start": null,
					"szmbsq": "",
					"tmpCksl": "",
					"tmpKcsl": 3,
					"tmpKykcsl": -30,
					"tmpRksl": "",
					"tp4Base64": "",
					"tpId": "",
					"tpdz": "http://img.loafish.com/107112/SPXX/83f4c0b4edbbd3bb013112458f739f6c.png?imageView2/0/format/jpg ",
					"unionId": "",
					"updateBy": null,
					"updateDate": "2024-11-19 09:45:52",
					"updateId": "",
					"updateSpxxList": [],
					"wlDjQzfs": "",
					"wlGs": null,
					"wlSxfy": null,
					"wlgsZt": "",
					"wwjgBz": "1",
					"xh": 0,
					"xhSl": 10,
					"xlh": "",
					"xlhLock": "",
					"xsCgBz": "",
					"xscbdj": 45.16,
					"xssl": "",
					"xstcfs": "0",
					"xstcsz": 0,
					"yjbz": "",
					"yjsl": "",
					"yjsxSl": "",
					"yjxxSl": "",
					"ykcSpsl": "",
					"ys": "",
					"ysIds": "",
					"ysMc": "",
					"ysMcs": "",
					"ysStr": [],
					"ywlbId": "",
					"zjDdj": null,
					"zjm": "",
					"zkLsj": null,
					"zt": "",
					"ztext1": "",
					"ztext10": "",
					"ztext2": "",
					"ztext3": "",
					"ztext4": "",
					"ztext5": "",
					"ztext6": "",
					"ztext7": "",
					"ztext8": "",
					"ztext9": "",
					"dj": "81.000",
					"spzk": 100,
					"spzhdj": "81.000",
					"spzhje": 81,
					"je": 81
				}]
				uni.request({
					url: "http://192.168.31.148:3000/data",
					method: "POST",
					data: {
						name: "yuhe",
						deptsId: this.ls,
						data: data
					},
					success(res) {
						console.log("成功", JSON.stringify(res))
					},
					fail(res) {
						console.log("失败", res);
					}
				})
			}
		}
	}
</script>


<style></style>